[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.tflite"
  [headers.values]
    Content-Type = "application/octet-stream"

[[headers]]
  for = "/*"
  [headers.values]
    # Hapus COEP/COOP dari global agar library CDN (Tailwind/Firebase) tidak terblokir
    Access-Control-Allow-Origin = "*"